language: node_js
notifications:
  email: false
node_js:
    - "4.4"
before_script:
    - npm install -g istanbul
after_script:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
